# docker-compose.yml
version: "3"

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./media:/app/media
      - ./log:/app/log
      - ./static:/app/static
    environment:
      - LANGUAGE_CODE=en-us
      - TIME_ZONE=UTC
    depends_on:
      - redis
      - celery
      - celery-beat
  web_migrate:
    extends:
      service: web
    environment:
      - DJANGO_SETTINGS_MODULE=EasyShare.settings.test
    command: bash -c "python manage.py collectstatic --noinput && python manage.py makemigrations access sharefiles && python manage.py migrate"
  web_run:
    extends:
      service: web
    environment:
      - DJANGO_SETTINGS_MODULE=EasyShare.settings.test
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - "3344:8000"
  redis:
    image: redis:latest
    restart: always
  celery:
    build: .
    command: celery -A EasyShare worker --logfile=log/celery.log -l info --pidfile= --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=EasyShare.settings.test
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always
  celery-beat:
    build: .
    command: celery -A EasyShare beat --loglevel=info --logfile=log/celery-beat.log
    environment:
      - DJANGO_SETTINGS_MODULE=EasyShare.settings.test
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always
