@hostname = localhost
@port = 8000
@host = {{hostname}}:{{port}}
@auth = Basic THN0cml2aW5nOjUyMDEzMTQuLlFx
@createdAt = {{$datetime iso8601}}

###
GET /easyshare/folder_detail/1
Authorization: {{auth}}
Host: {{host}}


### file detail
GET /easyshare/file_detail/2
Host: {{host}}
Authorization: {{auth}}


### no auth:403
POST /easyshare/folder/user HTTP/1.1
Host: {{host}}
Content-Type: application/json

{
    "name": "file",
    "password": "test",
    "user": 1
}


### Get created folder info
GET /easyshare/folder/user HTTP/1.1
Host: {{host}}
Authorization: {{auth}}


### Create a folder 
#  @prompt foldername
#  @prompt password folder password
POST /easyshare/folder/user HTTP/1.1
Host: {{host}}
Authorization: {{auth}}
Content-Type: application/json

{
    "name": "{{foldername}}",
    "password":"{{password}}"
}

### update password and name
# @prompt fold_id
# @prompt folder_name
# @prompt password
PUT /easyshare/folder_update/{{fold_id}} HTTP/1.1
Content-Type: application/json
Host: {{host}}
Authorization: Basic test:123456

{
    "name":"{{folder_name}}",
    "password":"{{password}}"
}


### upload a png file to folder(folder needs to be created)
# @prompt folder_id should be integer
# @prompt file_path local file path(can be relative)
# @prompt file_name should be precise and include file type
# @prompt file_type e.g png
POST /easyshare/file_upload/folder/{{folder_id}} HTTP/1.1
Host: {{host}}
Authorization: {{auth}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="upload"; filename="{{file_name}}"
Content-Type: image/png

< {{file_path}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

{{file_name}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="size"

0
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="type"

{{file_type}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="folder"

{{folder_id}}
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="user"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW--


### Creator view the folder files
GET /easyshare/folder_detail/1 HTTP/1.1
Content-Type: application/json
Authorization: {{auth}}
Host: {{host}}


### Shared folder
# @prompt foldername
# @prompt password
GET /easyshare/file/folder/1?name={{foldername}}&password={{password}} HTTP/1.1
Content-Type: application/json
Host: {{host}}


### Delete file
# @prompt id file_id, should be an integer
# @prompt username
# @prompt password
DELETE /easyshare/file_detail/{{id}}
Authorization: Basic {{username}}:{{password}}
Host: {{host}}



### Delete folder
# @prompt id folder_id, should be an integer
# @prompt username
# @prompt password
DELETE /easyshare/folder_remove/{{id}}
Authorization: Basic {{username}}:{{password}}
# Authorization: {{auth}}
Host: {{host}}

