# 
GET http://127.0.0.1:8000/easyshare/file/1

###
GET http://127.0.0.1:8000/easyshare/folder/1

###
GET http://127.0.0.1:8000/easyshare/file_detail/1

### no auth
POST http://127.0.0.1:8000/easyshare/folder/user HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "password": "123456",
    "creator": 1
}


### 
POST http://127.0.0.1:8000/easyshare/folder/user HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "password": "123456",
    "creator": 1
}

### 
GET http://127.0.0.1:8000/easyshare/folder_detail/1 HTTP/1.1
Content-Type: application/json

{
    "creator": 1
}
